- hosts: node
  become: true
  tasks:
    - name: create postgres deployment
      command: kubectl apply -f /home/ubuntu/postgres-deployment.yml
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config

    - name: create postgres service
      command: kubectl apply -f /home/ubuntu/postgres-service.yml
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config

    - name: create redis deployment
      command: kubectl apply -f /home/ubuntu/redis-deployment.yml
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config

    - name: create redis service
      command: kubectl apply -f /home/ubuntu/redis-service.yml
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config

    - name: create backend deployment
      command: kubectl apply -f /home/ubuntu/backend-deployment.yml
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config

    - name: create backend service
      command: kubectl apply -f /home/ubuntu/backend-service.yml
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config